#!/bin/bash


# Just in case we have no tree
rpmdev-setuptree

#tar czf ~/rpmbuild/SOURCES/projectrtp.tar.gz -C ./src .


# The folder container the source has to contain the version in the filename
tar czf ~/rpmbuild/SOURCES/projectrtp.tar.gz \
    --transform 's,src/,projectrtp-0/,' \
    --transform 's,LICENSE,projectrtp-0/LICENSE,' \
    ./src/* LICENSE

rpmbuild -ba projectrtp.spec
