#!/bin/bash
#
# There is a conflict between npm development (using links) and docker which refuses 
# to use links. Docker can use tar files to get round this - but podman crashes.
# The work around whilst we have this in development is to cretae a tmp out directory
#
# Note, this is an intermediate step - before we have stable sub packages which we can
# simply use npm to install in the container.

OUT="./_tmpbuild"
DOCKER="podman"

rm -rf $OUT
mkdir $OUT

cp -a Dockerfile $OUT
cp -a package*.json $OUT
cp -a index.js $OUT
cp -a LICENSE $OUT
cp -a README.md $OUT
cp -ar lib $OUT
cp -ar src $OUT
cp -ar stress $OUT
cp -ar test $OUT
cp -ar examples $OUT

mkdir $OUT/node_modules
cp -arL node_modules/* $OUT/node_modules

$DOCKER build $OUT -t projectrtp:1.0.0 -t projectrtp:latest


