// Codec module — port of projectrtpcodecx.
//
// Public JS API (via #[napi]):
//   linear162pcma / pcma2linear16
//   linear162pcmu / pcmu2linear16
//
// Impl is a direct port of spandsp's G.711 (linear_to_alaw / alaw_to_linear /
// linear_to_ulaw / ulaw_to_linear) so output is bit-for-bit identical to the
// C++ version's lookup tables (which were generated by calling spandsp).
//
// G.722 / iLBC live elsewhere — they stay FFI'd (out of scope for this module).

use napi::bindgen_prelude::*;
use napi_derive::napi;

#[inline]
fn top_bit(x: u32) -> i32 {
    if x == 0 { -1 } else { 31 - x.leading_zeros() as i32 }
}

pub fn linear_to_alaw(linear: i32) -> u8 {
    let (mut linear, mask) = if linear >= 0 {
        (linear, 0xD5i32)
    } else {
        (-linear - 8, 0x55i32)
    };
    if linear > 0x7F7B {
        linear = 0x7F7B;
    }
    let out = if linear >= 0x100 {
        let seg = top_bit((linear | 0xFF) as u32) - 7;
        ((seg << 4) | ((linear >> (seg + 3)) & 0xF)) ^ mask
    } else {
        ((linear >> 4) & 0xFF) ^ mask
    };
    out as u8
}

pub fn alaw_to_linear(alaw: u8) -> i16 {
    let a = alaw ^ 0x55;
    let mut i = ((a as i32 & 0x0F) << 4) as i32;
    let seg = (a as i32 & 0x70) >> 4;
    if seg != 0 {
        i = (i + 0x108) << (seg - 1);
    } else {
        i += 8;
    }
    if a & 0x80 != 0 { i as i16 } else { -(i as i16) }
}

pub fn linear_to_ulaw(linear: i32) -> u8 {
    let (mut linear, mask) = if linear < 0 {
        (0x84 - linear, 0x7Fi32)
    } else {
        (0x84 + linear, 0xFFi32)
    };
    if linear > 0x7FFF {
        linear = 0x7FFF;
    }
    let seg = top_bit((linear | 0xFF) as u32) - 7;
    let u_val = (seg << 4) | ((linear >> (seg + 3)) & 0xF);
    (u_val ^ mask) as u8
}

pub fn ulaw_to_linear(ulaw: u8) -> i16 {
    let u = !ulaw;
    let t = (((u as i32 & 0x0F) << 3) + 0x84) << ((u as i32 & 0x70) >> 4);
    if u & 0x80 != 0 { (0x84 - t) as i16 } else { (t - 0x84) as i16 }
}

// JS-facing wrappers — match existing single-sample API in index.js.
// The C++ side offsets linear input by +32768 (unsigned 16-bit index into a
// 65536-entry table) and bounds-checks. We preserve that behavior.

fn clamp_linear_index(val: i32) -> Option<i16> {
    let shifted = val + 32768;
    if !(0..=65535).contains(&shifted) { return None; }
    Some((shifted - 32768) as i16)
}

#[napi(namespace = "codecx", js_name = "linear162pcma")]
pub fn js_linear_to_pcma(sample: i32) -> Result<i32> {
    let s = clamp_linear_index(sample).ok_or_else(|| Error::from_reason("out of range"))?;
    Ok(linear_to_alaw(s as i32) as i32)
}

#[napi(namespace = "codecx", js_name = "pcma2linear16")]
pub fn js_pcma_to_linear(sample: i32) -> Result<i32> {
    if !(0..=255).contains(&sample) {
        return Err(Error::from_reason("out of range"));
    }
    Ok(alaw_to_linear(sample as u8) as i32)
}

#[napi(namespace = "codecx", js_name = "linear162pcmu")]
pub fn js_linear_to_pcmu(sample: i32) -> Result<i32> {
    let s = clamp_linear_index(sample).ok_or_else(|| Error::from_reason("out of range"))?;
    Ok(linear_to_ulaw(s as i32) as i32)
}

#[napi(namespace = "codecx", js_name = "pcmu2linear16")]
pub fn js_pcmu_to_linear(sample: i32) -> Result<i32> {
    if !(0..=255).contains(&sample) {
        return Err(Error::from_reason("out of range"));
    }
    Ok(ulaw_to_linear(sample as u8) as i32)
}

#[cfg(test)]
mod tests {
    use super::*;

    // Known vectors from ITU G.711 / spandsp. Zero / mid-scale / extremes.
    #[test]
    fn alaw_known_vectors() {
        // linear 0 → A-law 0xD5 (mid-code)
        assert_eq!(linear_to_alaw(0), 0xD5);
        // decode of 0xD5 rounds back to near-zero (small negative, -8)
        let decoded = alaw_to_linear(0xD5);
        assert!(decoded.abs() < 16, "0xD5 decoded to {decoded}");
    }

    #[test]
    fn ulaw_known_vectors() {
        // linear 0 → µ-law 0xFF
        assert_eq!(linear_to_ulaw(0), 0xFF);
        assert_eq!(ulaw_to_linear(0xFF), 0);
    }

    #[test]
    fn alaw_roundtrip_is_monotonic_and_small_error() {
        // Every linear16 sample, when round-tripped through alaw, should
        // recover within the quantization step for its segment (<= ~512).
        for s in (-32000i32..=32000).step_by(137) {
            let a = linear_to_alaw(s);
            let back = alaw_to_linear(a) as i32;
            let err = (back - s).abs();
            assert!(err <= 1024, "roundtrip err {err} too large for {s} -> {a:02X} -> {back}");
        }
    }

    #[test]
    fn ulaw_roundtrip_is_monotonic_and_small_error() {
        for s in (-32000i32..=32000).step_by(137) {
            let u = linear_to_ulaw(s);
            let back = ulaw_to_linear(u) as i32;
            let err = (back - s).abs();
            assert!(err <= 1024, "roundtrip err {err} too large for {s} -> {u:02X} -> {back}");
        }
    }

    #[test]
    fn alaw_all_bytes_decode() {
        // No panics across the full 256-entry space; sign bit mirrors MSB after XOR 0x55.
        for a in 0u8..=255 {
            let _ = alaw_to_linear(a);
        }
    }

    #[test]
    fn ulaw_all_bytes_decode() {
        for u in 0u8..=255 {
            let _ = ulaw_to_linear(u);
        }
    }
}
