// Codec module — port of projectrtpcodecx.
//
// Public JS API (via #[napi]):
//   linear162pcma / pcma2linear16
//   linear162pcmu / pcmu2linear16
//
// Impl is a direct port of spandsp's G.711 (linear_to_alaw / alaw_to_linear /
// linear_to_ulaw / ulaw_to_linear) so output is bit-for-bit identical to the
// C++ version's lookup tables (which were generated by calling spandsp).
//
// G.722 / iLBC live elsewhere — they stay FFI'd (out of scope for this module).

use std::sync::LazyLock;

use napi::bindgen_prelude::*;
use napi_derive::napi;

// ---- Pre-computed G.711 tables ----
//
// Both directions have tiny codomains so full tables are cheap and the
// hot path (per-sample encode/decode) reduces to a single load. The C++
// side does the same — generating these at startup via spandsp. At
// 1000 channels × 50 ticks/s × 160 samples/tick = 8M lookups/s, every
// saved instruction matters.
//
// Table sizes:
//   linear → alaw / ulaw : 65536 entries indexed by `(sample + 32768) as
//                          usize` (unsigned view of i16)
//   alaw   / ulaw → linear: 256 entries indexed by the compressed byte

const fn compute_linear_to_alaw(linear: i32) -> u8 {
    // Matches spandsp `linear_to_alaw` (g711.h) exactly — the negative
    // branch subtracts 1, not 8. An earlier port of this function used
    // `-linear - 8`, which silently encoded every negative sample ~7
    // below correct magnitude and full-scale-spiked for linear in -7..=-1
    // (that range gave `(-7..=-1) >> 4 = -1`, `& 0xFF = 0xFF`, `^ 0x55
    // = 0xAA` → decodes to +32256 on the other end).
    let (mut linear, mask) = if linear >= 0 {
        (linear, 0xD5i32)
    } else {
        (-linear - 1, 0x55i32)
    };
    if linear > 0x7F7B {
        linear = 0x7F7B;
    }
    let out = if linear >= 0x100 {
        // top_bit inlined as a const fn equivalent.
        let v = (linear | 0xFF) as u32;
        let seg = (31 - v.leading_zeros() as i32) - 7;
        ((seg << 4) | ((linear >> (seg + 3)) & 0xF)) ^ mask
    } else {
        ((linear >> 4) & 0xFF) ^ mask
    };
    out as u8
}

const fn compute_alaw_to_linear(alaw: u8) -> i16 {
    let a = alaw ^ 0x55;
    let mut i = (a as i32 & 0x0F) << 4;
    let seg = (a as i32 & 0x70) >> 4;
    if seg != 0 {
        i = (i + 0x108) << (seg - 1);
    } else {
        i += 8;
    }
    if a & 0x80 != 0 {
        i as i16
    } else {
        -(i as i16)
    }
}

const fn compute_linear_to_ulaw(linear: i32) -> u8 {
    let (mut linear, mask) = if linear < 0 {
        (0x84 - linear, 0x7Fi32)
    } else {
        (0x84 + linear, 0xFFi32)
    };
    if linear > 0x7FFF {
        linear = 0x7FFF;
    }
    let v = (linear | 0xFF) as u32;
    let seg = (31 - v.leading_zeros() as i32) - 7;
    let u_val = (seg << 4) | ((linear >> (seg + 3)) & 0xF);
    (u_val ^ mask) as u8
}

const fn compute_ulaw_to_linear(ulaw: u8) -> i16 {
    let u = !ulaw;
    let t = (((u as i32 & 0x0F) << 3) + 0x84) << ((u as i32 & 0x70) >> 4);
    if u & 0x80 != 0 {
        (0x84 - t) as i16
    } else {
        (t - 0x84) as i16
    }
}

// `table[i]` stores the compressed byte for `i as i16` (i.e. the sample
// obtained by reinterpreting the 16-bit index as signed). Accessors use
// `(sample as u16) as usize` as the index: sample 0 → 0, sample -1 →
// 0xFFFF, sample -32768 → 0x8000, etc.
static LINEAR_TO_ALAW: LazyLock<Box<[u8; 65536]>> = LazyLock::new(|| {
    let mut table = Box::new([0u8; 65536]);
    let mut i = 0usize;
    while i < 65536 {
        let sample = i as i16 as i32;
        table[i] = compute_linear_to_alaw(sample);
        i += 1;
    }
    table
});

static LINEAR_TO_ULAW: LazyLock<Box<[u8; 65536]>> = LazyLock::new(|| {
    let mut table = Box::new([0u8; 65536]);
    let mut i = 0usize;
    while i < 65536 {
        let sample = i as i16 as i32;
        table[i] = compute_linear_to_ulaw(sample);
        i += 1;
    }
    table
});

static ALAW_TO_LINEAR: LazyLock<[i16; 256]> = LazyLock::new(|| {
    let mut table = [0i16; 256];
    let mut i = 0usize;
    while i < 256 {
        table[i] = compute_alaw_to_linear(i as u8);
        i += 1;
    }
    table
});

static ULAW_TO_LINEAR: LazyLock<[i16; 256]> = LazyLock::new(|| {
    let mut table = [0i16; 256];
    let mut i = 0usize;
    while i < 256 {
        table[i] = compute_ulaw_to_linear(i as u8);
        i += 1;
    }
    table
});

#[inline]
pub fn linear_to_alaw(linear: i32) -> u8 {
    // Clamp to i16 range and fold the sign into an unsigned 16-bit index.
    let s = linear.clamp(i16::MIN as i32, i16::MAX as i32) as i16;
    LINEAR_TO_ALAW[(s as u16) as usize]
}

#[inline]
pub fn alaw_to_linear(alaw: u8) -> i16 {
    ALAW_TO_LINEAR[alaw as usize]
}

#[inline]
pub fn linear_to_ulaw(linear: i32) -> u8 {
    let s = linear.clamp(i16::MIN as i32, i16::MAX as i32) as i16;
    LINEAR_TO_ULAW[(s as u16) as usize]
}

// ---- Buffer-level transcode helpers ----
//
// Used by tick.rs's mix-relay path to transcode between PCMA/PCMU when two
// mixed channels speak different codecs.

#[allow(dead_code)]
pub fn encode_pcma_buf(samples: &[i16]) -> Vec<u8> {
    samples.iter().map(|&s| linear_to_alaw(s as i32)).collect()
}
#[allow(dead_code)]
pub fn decode_pcma_buf(payload: &[u8]) -> Vec<i16> {
    payload.iter().map(|&b| alaw_to_linear(b)).collect()
}
#[allow(dead_code)]
pub fn encode_pcmu_buf(samples: &[i16]) -> Vec<u8> {
    samples.iter().map(|&s| linear_to_ulaw(s as i32)).collect()
}
#[allow(dead_code)]
pub fn decode_pcmu_buf(payload: &[u8]) -> Vec<i16> {
    payload.iter().map(|&b| ulaw_to_linear(b)).collect()
}

/// Per-channel codec state + cached representations, à la C++ `codecx`.
///
/// The bundle holds:
/// - Stateful codec objects (G.722 enc/dec, iLBC enc/dec, LP filters) that
///   persist across ticks. Never cleared.
/// - Cached representations of the audio currently being processed: wire
///   bytes keyed by PT, linear samples at 8 kHz and 16 kHz. These are
///   invalidated on every `feed_*` call.
///
/// Consumers call `require_*` accessors to pull whichever representation
/// they need; the bundle computes it via the shortest conversion chain
/// from whatever input was fed, and caches the result so a second
/// consumer in the same tick doesn't re-compute.
///
/// Design points vs the old one-shot `decode`/`encode` API:
/// - **Lazy.** If no consumer needs the linear audio this tick
///   (same-codec pass-through with no recorder/bargein), the decode
///   stage is simply never run.
/// - **Cached.** Multiple consumers (mix frame, recorder, bargein
///   power, prebuffer) share one decode.
/// - **Dst-owned encode.** The encoder lives on the bundle of the
///   channel *sending* that codec (matches C++ `dstchan->outcodec`).
///   Callers funnel linear samples into the destination's bundle via
///   `feed_linear_8k` / `feed_linear_16k` and then `require_wire_as`.
pub struct CodecBundle {
    // ---- Stateful codec objects (persist across ticks) ----
    g722_encoder: Option<crate::g722::Encoder>,
    g722_decoder: Option<crate::g722::Decoder>,
    /// LP filter for 16 kHz → 8 kHz downsample after G.722 decode.
    /// Filter history is stateful — carrying it across packets avoids
    /// edge artefacts.
    g722_down_filter: crate::firfilter::Lowpass3_4k16k,
    /// LP filter for 8 kHz → 16 kHz upsample before G.722 encode.
    g722_up_filter: crate::firfilter::Lowpass3_4k16k,
    ilbc_encoder: Option<crate::ilbc::Encoder>,
    ilbc_decoder: Option<crate::ilbc::Decoder>,
    /// Dynamic RTP PTs that should be treated as iLBC by decode/encode.
    /// Slot 0 is the local side's configured iLBC wire PT; slot 1 is the
    /// mix peer's. Static PT 97 is always accepted.
    ilbc_pts: [u8; 2],
    /// Negotiated (SDP) RTP payload type for this channel, set at remote
    /// config — known before the first inbound packet decodes. Lets
    /// `is_wideband()` / `native_samplerate()` report wideband for a G.722
    /// channel even when no packet has set `wire_pt` yet (e.g. a `record`
    /// issued before media starts). 255 = not yet negotiated.
    negotiated_pt: u8,

    // ---- Input (one of these is set by a `feed_*` call) ----
    /// PT of the wire bytes currently held, or 255 if no wire input.
    wire_pt: u8,
    /// Raw wire bytes as received. Persistent allocation, cleared and
    /// refilled per `feed_wire`.
    wire_bytes: Vec<u8>,

    // ---- Cached representations (invalidated on every feed_*) ----
    narrowband_8k: Option<Vec<i16>>,
    wideband_16k: Option<Vec<i16>>,
    pcma_out: Option<Vec<u8>>,
    pcmu_out: Option<Vec<u8>>,
    g722_out: Option<Vec<u8>>,
    ilbc_out: Option<Vec<u8>>,
}

impl Default for CodecBundle {
    fn default() -> Self {
        Self::new()
    }
}

impl CodecBundle {
    pub fn new() -> Self {
        Self {
            g722_encoder: None,
            g722_decoder: None,
            g722_down_filter: crate::firfilter::Lowpass3_4k16k::new(),
            g722_up_filter: crate::firfilter::Lowpass3_4k16k::new(),
            ilbc_encoder: None,
            ilbc_decoder: None,
            ilbc_pts: [97, 97],
            negotiated_pt: 255,
            wire_pt: 255,
            wire_bytes: Vec::with_capacity(320),
            narrowband_8k: None,
            wideband_16k: None,
            pcma_out: None,
            pcmu_out: None,
            g722_out: None,
            ilbc_out: None,
        }
    }

    pub fn set_local_ilbc_pt(&mut self, pt: u8) {
        self.ilbc_pts[0] = pt;
    }
    pub fn set_peer_ilbc_pt(&mut self, pt: u8) {
        self.ilbc_pts[1] = pt;
    }

    /// Record the negotiated (SDP) RTP payload type. Drives the wideband
    /// classification before any packet has been decoded.
    pub fn set_negotiated_pt(&mut self, pt: u8) {
        self.negotiated_pt = pt;
    }

    fn is_ilbc_pt(&self, pt: u8) -> bool {
        pt == 97 || pt == self.ilbc_pts[0] || pt == self.ilbc_pts[1]
    }

    // ---- Cache invalidation -------------------------------------------------

    /// Clear every cached representation. Called at the start of every
    /// `feed_*` so stale values from a previous tick can't be returned.
    /// Stateful codec objects (encoders/decoders/filters) are NOT cleared.
    fn invalidate_caches(&mut self) {
        self.narrowband_8k = None;
        self.wideband_16k = None;
        self.pcma_out = None;
        self.pcmu_out = None;
        self.g722_out = None;
        self.ilbc_out = None;
    }

    // ---- Input (set one of these per tick) ---------------------------------

    /// Feed raw RTP-payload bytes for the given PT. Invalidates all
    /// cached representations. Subsequent `require_*` calls decode
    /// lazily from this wire input.
    pub fn feed_wire(&mut self, pt: u8, payload: &[u8]) {
        self.wire_pt = pt;
        self.wire_bytes.clear();
        self.wire_bytes.extend_from_slice(payload);
        self.invalidate_caches();
    }

    /// Feed 8 kHz linear samples. Used on the outbound path where the
    /// destination bundle is handed a peer's decoded contribution. The
    /// linear samples are stashed directly in the `narrowband_8k` cache
    /// so subsequent `require_wire_as(pt)` calls skip the decode step.
    pub fn feed_linear_8k(&mut self, samples: &[i16]) {
        self.wire_pt = 255;
        self.wire_bytes.clear();
        self.invalidate_caches();
        self.narrowband_8k = Some(samples.to_vec());
    }

    /// Feed 16 kHz linear samples. Rare — used when upstream code has
    /// already produced wideband audio (e.g. a 16 kHz source feeding a
    /// G.722 encoder without downsampling).
    #[allow(dead_code)]
    pub fn feed_linear_16k(&mut self, samples: &[i16]) {
        self.wire_pt = 255;
        self.wire_bytes.clear();
        self.invalidate_caches();
        self.wideband_16k = Some(samples.to_vec());
    }

    /// True if this channel is wideband (G.722, PT 9). Used to pick the
    /// channel's native PCM rate for recordings / readers. Considers both
    /// the live wire codec and the negotiated SDP codec, so a recorder
    /// opened before the first inbound G.722 packet is still stamped at
    /// 16 kHz — matching the wideband frames the feed path writes once
    /// media flows. Without the negotiated fallback the WAV header (8 kHz)
    /// and the 16 kHz audio disagreed and playback ran at half speed.
    pub fn is_wideband(&self) -> bool {
        self.wire_pt == 9 || self.negotiated_pt == 9
    }

    /// The channel's native PCM sample rate inferred from the wire codec:
    /// 16 kHz for G.722, 8 kHz otherwise (incl. before a codec is known).
    pub fn native_samplerate(&self) -> u32 {
        if self.is_wideband() {
            16000
        } else {
            8000
        }
    }

    // ---- Fast path: raw wire bytes if the PT matches -----------------------

    /// Return the wire bytes as-is iff `pt` matches the fed wire PT.
    /// Zero codec work — the basis for the same-codec pass-through
    /// optimisation in N=2 mix (when the destination wants exactly
    /// what the source sent, we can forward without transcoding).
    ///
    /// Not yet used in the call path — kept available so the N=2
    /// short-circuit can be wired up once the recorder-format check
    /// is in place (a pass-through forwards raw bytes which bypass
    /// the decoder; recorders expecting linear samples would get no
    /// audio in that case).
    #[allow(dead_code)]
    pub fn raw_wire_if_pt(&self, pt: u8) -> Option<&[u8]> {
        if self.wire_pt == 255 || self.wire_bytes.is_empty() {
            return None;
        }
        let match_ok = match pt {
            0 | 8 | 9 => pt == self.wire_pt,
            _ if self.is_ilbc_pt(pt) => self.is_ilbc_pt(self.wire_pt),
            _ => false,
        };
        if match_ok {
            Some(&self.wire_bytes)
        } else {
            None
        }
    }

    // ---- Lazy accessors ----------------------------------------------------

    /// 8 kHz linear samples. Compute from whatever input form we have,
    /// via the shortest chain. Cached on success.
    pub fn require_narrowband_8k(&mut self) -> Option<&[i16]> {
        if self.narrowband_8k.is_some() {
            return self.narrowband_8k.as_deref();
        }

        // Path 1: decode directly from wire PT.
        if !self.wire_bytes.is_empty() {
            if self.is_ilbc_pt(self.wire_pt) {
                let dec = self
                    .ilbc_decoder
                    .get_or_insert_with(|| crate::ilbc::Decoder::new().expect("ilbc decoder init"));
                if let Some(v) = dec.decode(&self.wire_bytes) {
                    self.narrowband_8k = Some(v);
                    return self.narrowband_8k.as_deref();
                }
                return None;
            }
            match self.wire_pt {
                0 => {
                    let v: Vec<i16> = self.wire_bytes.iter().map(|&b| ulaw_to_linear(b)).collect();
                    self.narrowband_8k = Some(v);
                    return self.narrowband_8k.as_deref();
                }
                8 => {
                    let v: Vec<i16> = self.wire_bytes.iter().map(|&b| alaw_to_linear(b)).collect();
                    self.narrowband_8k = Some(v);
                    return self.narrowband_8k.as_deref();
                }
                9 => {
                    // G.722: decode to wideband, then downsample. The
                    // wideband representation is cached first so a
                    // consumer wanting 16 kHz later doesn't re-decode.
                    self.require_wideband_16k()?;
                    let wb = self.wideband_16k.as_ref().unwrap();
                    let mut nb = Vec::with_capacity(wb.len() / 2);
                    g722_down_into(wb, &mut self.g722_down_filter, &mut nb);
                    self.narrowband_8k = Some(nb);
                    return self.narrowband_8k.as_deref();
                }
                _ => {}
            }
        }

        // Path 2: downsample from cached wideband.
        if let Some(wb) = self.wideband_16k.as_ref() {
            let mut nb = Vec::with_capacity(wb.len() / 2);
            g722_down_into(wb, &mut self.g722_down_filter, &mut nb);
            self.narrowband_8k = Some(nb);
            return self.narrowband_8k.as_deref();
        }

        None
    }

    /// 16 kHz linear samples. Native for G.722; used for 16 kHz
    /// recording. Computed by decoding G.722 wire OR upsampling from
    /// cached narrowband.
    pub fn require_wideband_16k(&mut self) -> Option<&[i16]> {
        if self.wideband_16k.is_some() {
            return self.wideband_16k.as_deref();
        }

        // Path 1: G.722 wire → wideband (decode only, no resample).
        if self.wire_pt == 9 && !self.wire_bytes.is_empty() {
            let dec = self
                .g722_decoder
                .get_or_insert_with(|| crate::g722::Decoder::new().expect("g722 decoder init"));
            let decoded = dec.decode(&self.wire_bytes);
            if !decoded.is_empty() {
                self.wideband_16k = Some(decoded.to_vec());
                return self.wideband_16k.as_deref();
            }
            return None;
        }

        // Path 2: upsample from narrowband (may itself require a decode).
        self.require_narrowband_8k()?;
        let nb = self.narrowband_8k.as_ref().unwrap();
        let mut wb = Vec::with_capacity(nb.len() * 2);
        g722_up_into(nb, &mut self.g722_up_filter, &mut wb);
        self.wideband_16k = Some(wb);
        self.wideband_16k.as_deref()
    }

    /// Produce wire bytes encoded as `pt` by pulling the best-available
    /// representation from `src` — the analogue of C++
    /// `dstchan->outcodec.write(srcchan->incodec)` where the destination
    /// decides what it wants from the source's bundle.
    ///
    /// Conversion chain, in preference order:
    /// 1. If `src.wire_pt == pt` → same codec on both ends, just copy
    ///    `src.wire_bytes` into our `out` cache for that PT. **Zero
    ///    codec work** (no decode, no encode, no resample). This is the
    ///    G.722↔G.722 and PCMA↔PCMA pass-through fast path.
    /// 2. If `pt` is G.722 → ask `src` for its 16 kHz wideband (may
    ///    already be cached from a recorder; otherwise decoded from
    ///    G.722 wire or upsampled from narrowband). Encode via our
    ///    persistent `g722_encoder`. Avoids the lossy 16→8→16 round
    ///    trip when both ends are G.722 but a consumer also wanted
    ///    narrowband.
    /// 3. Else → ask `src` for narrowband 8 kHz and encode to PCMA /
    ///    PCMU / iLBC via the appropriate stateful encoder on self.
    ///
    /// The encoder state (G.722 predictor, iLBC LP, up-sample filter)
    /// stays on `self` across ticks for a coherent outbound stream.
    pub fn encode_from(&mut self, pt: u8, src: &mut CodecBundle) -> Option<&[u8]> {
        // Fast path: same codec on both ends — copy src's wire bytes.
        if let Some(wire) = src.raw_wire_if_pt(pt) {
            let owned = wire.to_vec();
            match pt {
                0 => {
                    self.pcmu_out = Some(owned);
                    return self.pcmu_out.as_deref();
                }
                8 => {
                    self.pcma_out = Some(owned);
                    return self.pcma_out.as_deref();
                }
                9 => {
                    self.g722_out = Some(owned);
                    return self.g722_out.as_deref();
                }
                p if self.is_ilbc_pt(p) => {
                    self.ilbc_out = Some(owned);
                    return self.ilbc_out.as_deref();
                }
                _ => {}
            }
        }

        // G.722 encode: prefer src's wideband (if cached from recorder
        // or decoded from G.722 wire). Falls through to upsample from
        // src's narrowband when the source is a narrowband codec.
        if pt == 9 {
            let out: Vec<u8> = {
                let wb = src.require_wideband_16k()?;
                let enc = self
                    .g722_encoder
                    .get_or_insert_with(|| crate::g722::Encoder::new().expect("g722 encoder init"));
                let wire = enc.encode(wb);
                if wire.is_empty() {
                    return None;
                }
                wire.to_vec()
            };
            self.g722_out = Some(out);
            return self.g722_out.as_deref();
        }

        // Narrowband codecs (PCMA / PCMU / iLBC): pull src's narrowband.
        if self.is_ilbc_pt(pt) {
            let out: Option<Vec<u8>> = {
                let nb = src.require_narrowband_8k()?;
                let enc = self
                    .ilbc_encoder
                    .get_or_insert_with(|| crate::ilbc::Encoder::new().expect("ilbc encoder init"));
                enc.encode_20ms(nb)
            };
            self.ilbc_out = out;
            return self.ilbc_out.as_deref();
        }
        match pt {
            0 => {
                let nb = src.require_narrowband_8k()?;
                let out: Vec<u8> = nb.iter().map(|&s| linear_to_ulaw(s as i32)).collect();
                self.pcmu_out = Some(out);
                self.pcmu_out.as_deref()
            }
            8 => {
                let nb = src.require_narrowband_8k()?;
                let out: Vec<u8> = nb.iter().map(|&s| linear_to_alaw(s as i32)).collect();
                self.pcma_out = Some(out);
                self.pcma_out.as_deref()
            }
            _ => None,
        }
    }

    /// Wire bytes encoded as `pt`. Computes via the shortest chain from
    /// whatever input form is currently held. Cached so a repeat call
    /// with the same `pt` returns the previous result.
    pub fn require_wire_as(&mut self, pt: u8) -> Option<&[u8]> {
        if self.is_ilbc_pt(pt) {
            if self.ilbc_out.is_some() {
                return self.ilbc_out.as_deref();
            }
            self.require_narrowband_8k()?;
            let nb = self.narrowband_8k.as_ref().unwrap();
            let enc = self
                .ilbc_encoder
                .get_or_insert_with(|| crate::ilbc::Encoder::new().expect("ilbc encoder init"));
            let out = enc.encode_20ms(nb)?;
            self.ilbc_out = Some(out);
            return self.ilbc_out.as_deref();
        }
        match pt {
            0 => {
                if self.pcmu_out.is_some() {
                    return self.pcmu_out.as_deref();
                }
                self.require_narrowband_8k()?;
                let nb = self.narrowband_8k.as_ref().unwrap();
                let out: Vec<u8> = nb.iter().map(|&s| linear_to_ulaw(s as i32)).collect();
                self.pcmu_out = Some(out);
                self.pcmu_out.as_deref()
            }
            8 => {
                if self.pcma_out.is_some() {
                    return self.pcma_out.as_deref();
                }
                self.require_narrowband_8k()?;
                let nb = self.narrowband_8k.as_ref().unwrap();
                let out: Vec<u8> = nb.iter().map(|&s| linear_to_alaw(s as i32)).collect();
                self.pcma_out = Some(out);
                self.pcma_out.as_deref()
            }
            9 => {
                if self.g722_out.is_some() {
                    return self.g722_out.as_deref();
                }
                self.require_wideband_16k()?;
                let wb_samples = self.wideband_16k.as_ref().unwrap();
                let enc = self
                    .g722_encoder
                    .get_or_insert_with(|| crate::g722::Encoder::new().expect("g722 encoder init"));
                let wire = enc.encode(wb_samples);
                if wire.is_empty() {
                    return None;
                }
                self.g722_out = Some(wire.to_vec());
                self.g722_out.as_deref()
            }
            _ => None,
        }
    }
}

/// 16 kHz → 8 kHz downsample: for each pair of input samples, run both
/// through the shared LP filter (to update its state) and keep only the
/// filtered second sample. Output goes into the caller-provided buffer
/// (cleared first) so the hot path can reuse it across ticks. Matches
/// C++ `l16widetonarrowband`.
fn g722_down_into(
    wideband: &[i16],
    filter: &mut crate::firfilter::Lowpass3_4k16k,
    out: &mut Vec<i16>,
) {
    out.clear();
    out.reserve(wideband.len() / 2);
    let mut i = 0;
    while i + 1 < wideband.len() {
        let _ = filter.execute(wideband[i]);
        out.push(filter.execute(wideband[i + 1]));
        i += 2;
    }
}

/// 8 kHz → 16 kHz upsample: for each input sample, emit the filtered
/// sample and then a filtered zero. Zero-interleaved upsampling: the LP
/// filter smooths the resulting spectrum's replicas. Output is written
/// into the caller-provided buffer. Matches C++ `l16lowtowideband`.
fn g722_up_into(
    narrowband: &[i16],
    filter: &mut crate::firfilter::Lowpass3_4k16k,
    out: &mut Vec<i16>,
) {
    out.clear();
    out.reserve(narrowband.len() * 2);
    for &s in narrowband {
        out.push(filter.execute(s));
        out.push(filter.execute(0));
    }
}

#[inline]
pub fn ulaw_to_linear(ulaw: u8) -> i16 {
    ULAW_TO_LINEAR[ulaw as usize]
}

// JS-facing wrappers — match existing single-sample API in index.js.
// The C++ side offsets linear input by +32768 (unsigned 16-bit index into a
// 65536-entry table) and bounds-checks. We preserve that behavior.

fn clamp_linear_index(val: i32) -> Option<i16> {
    let shifted = val + 32768;
    if !(0..=65535).contains(&shifted) {
        return None;
    }
    Some((shifted - 32768) as i16)
}

#[cfg_attr(not(test), napi(namespace = "codecx", js_name = "linear162pcma"))]
pub fn js_linear_to_pcma(sample: i32) -> Result<i32> {
    let s = clamp_linear_index(sample).ok_or_else(|| Error::from_reason("out of range"))?;
    Ok(linear_to_alaw(s as i32) as i32)
}

#[cfg_attr(not(test), napi(namespace = "codecx", js_name = "pcma2linear16"))]
pub fn js_pcma_to_linear(sample: i32) -> Result<i32> {
    if !(0..=255).contains(&sample) {
        return Err(Error::from_reason("out of range"));
    }
    Ok(alaw_to_linear(sample as u8) as i32)
}

#[cfg_attr(not(test), napi(namespace = "codecx", js_name = "linear162pcmu"))]
pub fn js_linear_to_pcmu(sample: i32) -> Result<i32> {
    let s = clamp_linear_index(sample).ok_or_else(|| Error::from_reason("out of range"))?;
    Ok(linear_to_ulaw(s as i32) as i32)
}

#[cfg_attr(not(test), napi(namespace = "codecx", js_name = "pcmu2linear16"))]
pub fn js_pcmu_to_linear(sample: i32) -> Result<i32> {
    if !(0..=255).contains(&sample) {
        return Err(Error::from_reason("out of range"));
    }
    Ok(ulaw_to_linear(sample as u8) as i32)
}

#[cfg(test)]
mod tests {
    use super::*;

    // Known vectors from ITU G.711 / spandsp. Zero / mid-scale / extremes.
    #[test]
    fn alaw_known_vectors() {
        // linear 0 → A-law 0xD5 (mid-code)
        assert_eq!(linear_to_alaw(0), 0xD5);
        // decode of 0xD5 rounds back to near-zero (small negative, -8)
        let decoded = alaw_to_linear(0xD5);
        assert!(decoded.abs() < 16, "0xD5 decoded to {decoded}");
    }

    #[test]
    fn ulaw_known_vectors() {
        // linear 0 → µ-law 0xFF
        assert_eq!(linear_to_ulaw(0), 0xFF);
        assert_eq!(ulaw_to_linear(0xFF), 0);
    }

    #[test]
    fn alaw_roundtrip_is_monotonic_and_small_error() {
        // Every linear16 sample, when round-tripped through alaw, should
        // recover within the quantization step for its segment (<= ~512).
        for s in (-32000i32..=32000).step_by(137) {
            let a = linear_to_alaw(s);
            let back = alaw_to_linear(a) as i32;
            let err = (back - s).abs();
            assert!(
                err <= 1024,
                "roundtrip err {err} too large for {s} -> {a:02X} -> {back}"
            );
        }
    }

    #[test]
    fn alaw_roundtrip_near_zero_exhaustive() {
        // Covers every value in the lowest A-law bin so an off-by-one sign
        // mistake can't reappear — the coarser `step_by(137)` test skipped
        // -7..=-1 and silently shipped a bug that encoded those to 0xAA
        // (+32256 on decode) for ~ half a year.
        for s in -64i32..=64 {
            let a = linear_to_alaw(s);
            let back = alaw_to_linear(a) as i32;
            let err = (back - s).abs();
            assert!(
                err <= 16,
                "near-zero roundtrip err {err} for {s} -> {a:02X} -> {back}"
            );
        }
    }

    #[test]
    fn ulaw_roundtrip_is_monotonic_and_small_error() {
        for s in (-32000i32..=32000).step_by(137) {
            let u = linear_to_ulaw(s);
            let back = ulaw_to_linear(u) as i32;
            let err = (back - s).abs();
            assert!(
                err <= 1024,
                "roundtrip err {err} too large for {s} -> {u:02X} -> {back}"
            );
        }
    }

    #[test]
    fn alaw_all_bytes_decode() {
        // No panics across the full 256-entry space; sign bit mirrors MSB after XOR 0x55.
        for a in 0u8..=255 {
            let _ = alaw_to_linear(a);
        }
    }

    #[test]
    fn ulaw_all_bytes_decode() {
        for u in 0u8..=255 {
            let _ = ulaw_to_linear(u);
        }
    }

    #[test]
    fn native_samplerate_follows_codec() {
        let mut cx = CodecBundle::new();
        // Before any codec is known, default to narrowband.
        assert!(!cx.is_wideband());
        assert_eq!(cx.native_samplerate(), 8000);
        // G.722 (PT 9) is wideband -> 16 kHz.
        cx.feed_wire(9, &[0u8; 80]);
        assert!(cx.is_wideband());
        assert_eq!(cx.native_samplerate(), 16000);
        // PCMA (PT 8) is narrowband -> 8 kHz.
        cx.feed_wire(8, &[0u8; 160]);
        assert!(!cx.is_wideband());
        assert_eq!(cx.native_samplerate(), 8000);
    }
}
