#!/bin/bash
#
# Requires the RPM to be genererated and stored in rpmbuild directory

filedate=$(date +%Y-%m-%d)
container=$(buildah from registry.fedoraproject.org/fedora:34)

buildah config --created-by "babblevoice"  $container
buildah config --author "nick at babblevoice.com @babblevoip" --label name=projectrtp:fedora-$filedate $container

buildah copy $container ~/rpmbuild/RPMS/x86_64/projectrtp-0-1.fc34.x86_64.rpm /tmp
buildah copy $container ./build-projectrtp-inside /tmp

buildah run $container -- /tmp/build-projectrtp-inside

buildah commit --format=docker $container projectrtp:fedora-$filedate
